<center>
    <img src="https://gitlab.com/ibm/skills-network/courses/placeholder101/-/raw/master/labs/module%201/images/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

# Peer Review Assignment - Data Engineer - Extract API Data

Estimated time needed: **20** minutes

## Objectives

In this part you will:

*   Collect exchange rate data using an API
*   Store the data as a CSV

For this lab, we are going to be using Python and several Python libraries. Some of these libraries might be installed in your lab environment or in SN Labs. Others may need to be installed by you. The cells below will install these libraries when executed.

In [1]:
#!pip install pandas
#!pip install requests

## Imports

Import any additional libraries you may need here.

In [2]:
import requests
import pandas as pd

## Extract Data Using an API

Using ExchangeRate-API we will extract currency exchange rate data. Use the below steps to get the access key and to get the data.

1.  Open the url : [https://exchangeratesapi.io/](https://exchangeratesapi.io/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0221ENSkillsNetwork23455645-2021-01-01) and create a free account.
2.  Once the account is created. You will get the Get the Free API key option on the top as shown below:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Final%20Assignment/Images/getapi.png"/>

3.  Copy the API key and use in the url in Question 1.

### Call the API

<b> Question 1</b> Using the `requests` library call the endpoint given above and save the text, remember the first few characters of the output:

In [3]:
# Write your code here
url = "http://api.exchangeratesapi.io/v1/latest?base=EUR&access_key=3ae8a41ae8b314fe2c76abee00969ef2"  #Make sure to change ******* to your API key.
response = requests.get(url)
response.json()

{'success': True,
 'timestamp': 1720417084,
 'base': 'EUR',
 'date': '2024-07-08',
 'rates': {'AED': 3.975088,
  'AFN': 76.950778,
  'ALL': 100.251014,
  'AMD': 420.339206,
  'ANG': 1.95092,
  'AOA': 938.866105,
  'ARS': 990.805354,
  'AUD': 1.604526,
  'AWG': 1.950775,
  'AZN': 1.837542,
  'BAM': 1.955982,
  'BBD': 2.185622,
  'BDT': 127.201864,
  'BGN': 1.950641,
  'BHD': 0.40794,
  'BIF': 3115.276178,
  'BMD': 1.082261,
  'BND': 1.46133,
  'BOB': 7.480698,
  'BRL': 5.925834,
  'BSD': 1.082511,
  'BTC': 1.9536379e-05,
  'BTN': 90.417433,
  'BWP': 14.688149,
  'BYN': 3.542536,
  'BYR': 21212.314528,
  'BZD': 2.181922,
  'CAD': 1.476372,
  'CDF': 3101.75958,
  'CHF': 0.969055,
  'CLF': 0.036697,
  'CLP': 1012.595523,
  'CNY': 7.86706,
  'CNH': 7.886836,
  'COP': 4433.417027,
  'CRC': 568.605751,
  'CUC': 1.082261,
  'CUP': 28.679915,
  'CVE': 110.275286,
  'CZK': 25.141465,
  'DJF': 192.731949,
  'DKK': 7.459257,
  'DOP': 64.030648,
  'DZD': 145.259963,
  'EGP': 51.898526,
  'ERN': 16.233914,
  'ETB': 62.517232,
  'EUR': 1,
  'FJD': 2.417991,
  'FKP': 0.849144,
  'GBP': 0.844937,
  'GEL': 2.992405,
  'GGP': 0.849144,
  'GHS': 16.671555,
  'GIP': 0.849144,
  'GMD': 73.323591,
  'GNF': 9321.094268,
  'GTQ': 8.411785,
  'GYD': 226.491125,
  'HKD': 8.454303,
  'HNL': 26.808271,
  'HRK': 7.595781,
  'HTG': 143.282702,
  'HUF': 392.936528,
  'IDR': 17595.614901,
  'ILS': 3.997277,
  'IMP': 0.849144,
  'INR': 90.352015,
  'IQD': 1418.132273,
  'IRR': 45549.65424,
  'ISK': 149.28665,
  'JEP': 0.849144,
  'JMD': 169.13171,
  'JOD': 0.767101,
  'JPY': 173.846281,
  'KES': 138.031789,
  'KGS': 92.996237,
  'KHR': 4458.395249,
  'KMF': 491.888698,
  'KPW': 974.034993,
  'KRW': 1495.543677,
  'KWD': 0.331151,
  'KYD': 0.902184,
  'KZT': 518.078323,
  'LAK': 23911.241823,
  'LBP': 96941.080401,
  'LKR': 329.893336,
  'LRD': 210.432128,
  'LSL': 19.726099,
  'LTL': 3.195636,
  'LVL': 0.654649,
  'LYD': 5.272053,
  'MAD': 10.684597,
  'MDL': 19.268195,
  'MGA': 4849.04904,
  'MKD': 61.604239,
  'MMK': 3515.141334,
  'MNT': 3733.800367,
  'MOP': 8.709112,
  'MRU': 42.899434,
  'MUR': 51.039564,
  'MVR': 16.731594,
  'MWK': 1877.018983,
  'MXN': 19.55472,
  'MYR': 5.097987,
  'MZN': 68.934654,
  'NAD': 19.726099,
  'NGN': 1678.283922,
  'NIO': 39.852981,
  'NOK': 11.429233,
  'NPR': 144.655463,
  'NZD': 1.762392,
  'OMR': 0.416649,
  'PAB': 1.082601,
  'PEN': 4.106883,
  'PGK': 4.168042,
  'PHP': 63.376118,
  'PKR': 301.337048,
  'PLN': 4.286133,
  'PYG': 8157.082496,
  'QAR': 3.950869,
  'RON': 4.975913,
  'RSD': 117.020533,
  'RUB': 95.400083,
  'RWF': 1427.114433,
  'SAR': 4.060735,
  'SBD': 9.129738,
  'SCR': 15.125677,
  'SDG': 650.439176,
  'SEK': 11.368524,
  'SGD': 1.459678,
  'SHP': 1.367382,
  'SLE': 24.726744,
  'SLL': 22694.472967,
  'SOS': 614.724574,
  'SRD': 32.684825,
  'STD': 22400.616492,
  'SVC': 9.472884,
  'SYP': 2719.213554,
  'SZL': 19.719199,
  'THB': 39.437466,
  'TJS': 11.534876,
  'TMT': 3.787913,
  'TND': 3.380315,
  'TOP': 2.547913,
  'TRY': 35.342203,
  'TTD': 7.329074,
  'TWD': 35.054861,
  'TZS': 2876.022001,
  'UAH': 43.886344,
  'UGX': 4004.373498,
  'USD': 1.082261,
  'UYU': 43.63407,
  'UZS': 13623.270678,
  'VEF': 3920547.130338,
  'VES': 36.086102,
  'VND': 27506.744186,
  'VUV': 128.488157,
  'WST': 3.030996,
  'XAF': 655.963634,
  'XAG': 0.034868,
  'XAU': 0.000454,
  'XCD': 2.924865,
  'XDR': 0.822208,
  'XOF': 655.963634,
  'XPF': 119.331742,
  'YER': 270.971095,
  'ZAR': 19.670852,
  'ZMK': 9741.656252,
  'ZMW': 26.548268,
  'ZWL': 348.487583}}

### Save as DataFrame

<b> Question 2</b>  Using the data gathered turn it into a `pandas` dataframe. The dataframe should have the Currency as the index and `Rate` as their columns. Make sure to drop unnecessary columns.

In [4]:
# Turn the data into a dataframe
dataframe = pd.DataFrame(response.json())
dataframe

     success   timestamp base        date        rates
AED     True  1720417084  EUR  2024-07-08     3.975088
AFN     True  1720417084  EUR  2024-07-08    76.950778
ALL     True  1720417084  EUR  2024-07-08   100.251014
AMD     True  1720417084  EUR  2024-07-08   420.339206
ANG     True  1720417084  EUR  2024-07-08     1.950920
..       ...         ...  ...         ...          ...
YER     True  1720417084  EUR  2024-07-08   270.971095
ZAR     True  1720417084  EUR  2024-07-08    19.670852
ZMK     True  1720417084  EUR  2024-07-08  9741.656252
ZMW     True  1720417084  EUR  2024-07-08    26.548268
ZWL     True  1720417084  EUR  2024-07-08   348.487583

[171 rows x 5 columns]

In [5]:
# Drop unnescessary columns
dataframe.drop(columns=["success", "timestamp", "base", "date"], inplace=True)
dataframe

           rates
AED     3.975088
AFN    76.950778
ALL   100.251014
AMD   420.339206
ANG     1.950920
..           ...
YER   270.971095
ZAR    19.670852
ZMK  9741.656252
ZMW    26.548268
ZWL   348.487583

[171 rows x 1 columns]

### Load the Data

Using the dataframe save it as a CSV names `exchange_rates_1.csv`.

In [7]:
# Save the Dataframe
dataframe.to_csv("exchange_rates_1.csv")

Your CSV should be in this format with more currencies

|     | Rates      |
| --- | ---------- |
| AED | 4.398618   |
| AFN | 92.917693  |
| ALL | 123.099093 |
| AMD | 621.935674 |
| ANG | 2.149648   |

## Authors

Ramesh Sannareddy, Joseph Santarcangelo and Azim Hirjani

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2021-04-15        | 0.2     | Malika            | Updated the lab from USD to EUR    |
| 2020-11-25        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0221ENSkillsNetwork23455645-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).